/************************************************************
 * This is a sample file generated by `codegen.py`, where   *
 * the number of elements is 1 and the number of runs is 1. *
 ************************************************************/

// This file was auto-generated by `codegen.py`.
// Do not modify it manually unless there is good reason to.

#include <chrono>
#include <concepts>
#include <iostream>
#include <numeric>
#include <string_view>
#include <type_traits>
#include <vector>

// Checks that some functor Func can be invoked at compile time on a std::vector
// containing elements of type T.
//
// Usage of std::bool_constant was inspired by stackoverflow question 63326542.
template <typename Func, typename T>
concept CompileTimeInvocable = requires (Func f) {
    { std::bool_constant<(Func()(std::vector<T>{}), true)>() };
    { Func()(std::vector<T>{}) } -> std::same_as<T>;
};

// Wrapper around the std::is_arithmetic type trait.
template <typename T>
concept Arithmetic = std::is_arithmetic_v<T>;

// Functor that sums the elements of a vector.
template <Arithmetic T>
struct SimpleSum {
    constexpr T operator()(const std::vector<T>& v) {
        return std::accumulate(v.begin(), v.end(), static_cast<T>(0));
    }
};

// Functor that multiplies the elements of a vector (while taking mod 1e9).
template <Arithmetic T>
struct SimpleProd {
    constexpr T operator()(const std::vector<T>& v) {
        return std::accumulate(v.begin(), v.end(), static_cast<T>(1),
            [](const T& accum, const T& elem) -> T {
                return (accum * elem) % static_cast<T>(1e9);
            }
        );
    }
};

// Populates a std::vector, then performs some computation over its elements.
// This function is executed at compile time.
//
// To obtain statistics on runtime, time how long it takes for a call to this
// function to be completed. We don't do the timing inside this function,
// because reading the current system time can only be done at runtime.
//
// @tparam Func the computation to be executed
// @tparam T the type of elements in the std::vector
template <typename Func, typename T>
requires CompileTimeInvocable<Func, T>
consteval  T doComputation() {
    // The repeated statements are ugly, but we need to explicitly add each
    // individual element rather than using a std::random_device and a loop so
    // that the function can be executed at compile time.
    std::vector<T> v;
    v.emplace_back(-861940221);


    return Func()(v);
}

// Wrapper over `doComputation` that:
// (1) executes the test `numRuns` number of times
// (2) times each function call and prints the relevant results
template <typename Func, typename T>
void runTestCase(int numRuns, std::string_view testName) {
    for (int i = 0; i < numRuns; ++i) {
        auto start = std::chrono::high_resolution_clock::now();
        T res = doComputation<Func, T>();
        auto end = std::chrono::high_resolution_clock::now();
        std::cout << testName << " result: " << res << "\n";
        std::cout << testName << " timing: " << (end-start).count() << " ns\n";
    }
    std::cout << "\n";
}

int main() {
    using namespace std::literals;

    int numRuns = 1;
    runTestCase<SimpleSum<long long>, long long>(numRuns, "SimpleSum"sv);
    runTestCase<SimpleProd<long long>, long long>(numRuns, "SimpleProd"sv);
}
